name: blackbox-exporter

services:
  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    restart: unless-stopped
    command:
      - --config.file=/etc/blackbox_exporter/config.yml
    volumes:
      - ./observability/blackbox/blackbox.yml:/etc/blackbox_exporter/config.yml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - observability_net

networks:
  observability_net:
    driver: bridge
    external: true
