services:
  frontend:
    image: course-frontend:day2-insecure
    build:
      context: ./frontend
      dockerfile: Dockerfile.insecure
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    image: course-backend:day2-insecure
    build:
      context: ./backend
      dockerfile: Dockerfile.insecure
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      ENABLE_DEBUG_ROUTES: "true"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:18
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./db/init:/docker-entrypoint-initdb.d:ro

  redis:
    image: redis:8
    ports:
      - "6379:6379"

  socket-breakout:
    image: docker:28-cli
    profiles: ["escape"]
    command: ["sh", "-c", "sleep infinity"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  host-breakout:
    image: alpine:3.21
    profiles: ["escape"]
    privileged: true
    pid: host
    command: ["sh", "-c", "sleep infinity"]
    volumes:
      - /:/host

volumes:
  postgres_data:
